### ISSUE TITLE
A doubt more than an issue. 

### ISSUE THREAD

**Issue by onurbamaro** [tspvivek/refine-directus#8]
Hello! Thank you for updating the Directus SDK.

I noticed that you employ legacy methods in the authentication flow. I'm wondering if it's acceptable to use an alternative authentication method, such as cookies, and utilize the package solely as a data provider?

**Comment by tspvivek** [comment]
Yes its possible, In example, I have used localstorage here in [directusClient.ts](https://github.com/tspvivek/refine-directus/blob/master/example/src/directusClient.ts), its upto you to decide the authentication flow.
Also [authprovider]((https://github.com/tspvivek/refine-directus/blob/master/example/src/authProvider.ts)) is only part of example, you can modify it to use latest AuthProvider from refine instead of legacy. I will update example with new AuthProvider soon.
